version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sammy
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  shyftlabs-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shyftlabs-api
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    restart: always

  prisma-studio:
    container_name: prisma-studio
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5555:5555"

volumes:
  postgres-data:
  # pgadmin-data:
