version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: richard
      POSTGRES_PASSWORD: graphql
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  shyftlabs-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shyftlabs-api
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    restart: always

volumes:
  postgres-data:
